### PR TITLE
Showing Event Details in CardView

### LINKED ISSUE #96: Show Events in CardView
vAll Events should be displayed in CardView. It is to be implemented as Event Brite App.

Would You like to work on this issue?
Yes

### PR DESCRIPTION
**Pull request by SIMRAN1**
Fixes #96 
Events are shown in Card view
image

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@imjog @chashmeetsingh please review!

**Review by jogendra — CHANGES_REQUESTED** [review]
- Make cards little bigger, looking squashed (Give some padding)
- Star is overlapping the title
- Make shadow little light, it is looking darker

**Comment by SIMRAN1** [comment]
okk @imjog !!

**Comment by SIMRAN1** [comment]
@imjog please review! . I apologise for late response!

**Comment by jogendra** [comment]
@SIMRAN1 Please post updated screenshot

**Comment by SIMRAN1** [comment]
image

**Comment by jogendra** [comment]
@SIMRAN1 TBF, It was looking good without using `CardView`

**Comment by SIMRAN1** [comment]
@imjog  actually have made this PR to only add cardview effect . I have already send another pr with redesigned card views please review it!

**Comment by SIMRAN1** [comment]
@imjog  done the changes!

**Comment by vimalcvs** [comment]
Nice work

**Pull request closed without merging**
