### PR TITLE
Showing Optional values in TableView Cell

### LINKED ISSUE #62: Showing optional values in table cells
In table cells, time of events is showing as optional, `Optional("07:05")`. Optional unwrapping should be done in a good way.

simulator screen shot - iphone 8 - 2018-05-07 at 01 36 51

### PR DESCRIPTION
**Pull request by SIMRAN1**
Fixes #62 
Optional values are unwrapped and displayed in TableView Cells.
image

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@imjog @chashmeetsingh please review it!

**Review by chashmeetsingh — APPROVED** [review]

**Review by jogendra — APPROVED** [review]

**Comment by jogendra** [comment]
@SIMRAN1 please merge `upstream/master` in your branch `issue#62` so that test can pass.

**Comment by SIMRAN1** [comment]
okk @imjog !!

**Review by jogendra — COMMENTED** [review]
@SIMRAN1 to merge upstream:
```
1. git remote add upstream https://github.com/fossasia/susi_iOS.git
2. git fetch upstream
3. git rebase upstream/master
and finally
git push -f origin issue#62
```

**Comment by SIMRAN1** [comment]
@imjog  I have rebased the branch!!
git pull --rebase upstream development
Actually problem is still the same because declaration  var refreshControl = UIRefreshControl() should be in Dispatch queue.

**Comment by jogendra** [comment]
@SIMRAN1 The main branch is `master`, rebase with `master`, not `development`.

**Comment by SIMRAN1** [comment]
okk @imjog !!

**Comment by jogendra** [comment]
@SIMRAN1 I put declaration var refreshControl = UIRefreshControl()  in Dispatch queue in last PR and it is merged into development so merging development should solve the issue.

Also main branch is `development`, my mistake.

Have you hard push?

**Comment by SIMRAN1** [comment]
@imjog I have already rebased on development but still test are failing!!Yes I have used git push -f!!

**Comment by ghost** [comment]
Hi @SIMRAN1!

It looks like one or more of your builds have failed.
I've added the relevant info below to save you some time.

- [Build 139.1](https://travis-ci.org/fossasia/open-event-ios/jobs/385941617) has `failed`

**Comment by chashmeetsingh** [comment]
This error is quite common in Travis, had the same issues with Susi so switched to CircleCI for it. Implementation looks good though, merging it.

**Comment by SIMRAN1** [comment]
Thanks @chashmeetsingh I tried many times solving this test cases issue!!

**Pull request merged**
