### PR TITLE
Show Events in redesigned cardview and make layout for displaying events

### LINKED ISSUE #108: Create Layout for Showing Location wise Events.
Create Layout for Showing Location wise Events.Location wise events should be loaded.

Would you like to work on this issue?
Yes

### PR DESCRIPTION
**Pull request by SIMRAN1**
Fixes #108 #107 #111 
Events to be displayed in card view and loaded from Server.
image

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@imjog @chashmeetsingh please review!

**Review by jogendra — CHANGES_REQUESTED** [review]
- The image is shrinking in cards
- Only left shadow is showing - Make cards shadow look like AppStore cards
- Increase corner radius a bit

**Comment by SIMRAN1** [comment]
@imjog @chashmeetsingh please review and merge this PR as it is acting blocker for other PRs.I will be doing other PR for minor changes but I request you to merge this PR.

**Comment by jogendra** [comment]
Looking very weired. Please look into it
simulator screen shot - iphone 8 - 2018-08-07 at 15 48 01

**Comment by SIMRAN1** [comment]
okk @imjog !!

**Comment by SIMRAN1** [comment]
Done the changes @imjog !

**Comment by SIMRAN1** [comment]
@imjog please review!

**Comment by jogendra** [comment]
@SIMRAN1  Still I am seeing this:
simulator screen shot - iphone 8 - 2018-08-19 at 20 35 45

**Pull request closed without merging**
