### PR TITLE
updating pod to latest version

### LINKED ISSUE #64: Update pod version to the latest
Currently, Open Event iOS is using `1.5.0` cocapods version. The latest version `1.5.2` is available so the need to upgrade to the latest.

### PR DESCRIPTION
**Pull request by SIMRAN1**
Fixes #64 
Pods need to be updated to latest version 1.5.2 . Current version of pods is 1.5.0

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@imjog @chashmeetsingh please review the pr!

**Review by jogendra — COMMENTED** [review]
@SIMRAN1 tests are failing!

**Comment by SIMRAN1** [comment]
@imjog I am resolving  it !

**Review by jogendra — CHANGES_REQUESTED** [review]
Please update all the pods to the latest version available for 1.5.2.

**Comment by ghost** [comment]
Hi @SIMRAN1!

It looks like one or more of your builds have failed.
I've added the relevant info below to save you some time.

- [Build 106.1](https://travis-ci.org/fossasia/open-event-ios/jobs/381670404) has `failed`

**Comment by SIMRAN1** [comment]
@imjog done the changes mentioned!

**Review by jogendra — APPROVED** [review]

**Pull request merged**
