### PR TITLE
Implemented best practices and project structure, fix data loading and UITests, update event model and cocoapods

### PR DESCRIPTION
**Pull request by jogendra**
**Fixed** #28  #53 and part of #30 

**Changes:**
- Restructured project folder structure
- Updated project settings
- Moved all files constants to `Constants.swift` file
- Removed outdated UITests
- Apply Linting
- Fix data loading
- Update event model with new track IDs
- Storyboard loading identifiers issue
- Updated cocoapods to latest 1.5.0

### CODE REVIEW

**Review by chashmeetsingh — APPROVED** [review]
Please squash your commits. @imjog

**Review by jurvis — APPROVED** [review]
update Cocoapods to 1.5.0? otherwise, lgtm.

**Comment by jurvis** [comment]
:shipit:

**Comment by jogendra** [comment]
@jurvis @chashmeetsingh @mariobehling Done! Please merge.

**Pull request merged**
