### PR TITLE
fossAsia

### PR DESCRIPTION
**Pull request by GodsEye-07**
i have made a few changes in the appearence of the app , merge this so that i can add more of the changes to it

### CODE REVIEW

**Comment by mariobehling** [comment]
Please open an issue first to show what you are changing and follow Best Practices: http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ Thanks.

**Comment by chashmeetsingh** [comment]
Hi @GodsEye-07, 
It seems that this PR shows a many of the old commits which shouldn't be present here. An easy way to fix this is to create an upstream and merge back from the main repo. Try following the steps below:

```
git remote add upstream https://github.com/fossasia/open-event-ios
git fetch upstream
git rebase upstream/development
git push -f origin
```

Also, there doesn't exist any commit from you in the PR, please look into that. And as Mario suggested, please follow the best practices so it's easy for the reviewers to review your work and merge it faster. 

Thanks!

**Comment by GodsEye-07** [comment]
hi @chashmeetsingh  
i am currently learning to use github properly and have the least idea how to do 
i just want to be the part of the FossAsia's open source development organisation

**Comment by chashmeetsingh** [comment]
Hey. Sure, take your time and do let us know if you get stuck at any point, we'll help.

**Comment by mariobehling** [comment]
I am closing this due to inactivity. Please open a new PR if any. Cheers.

**Pull request closed without merging**
