### PR TITLE
show case implemented in add to calender button

### PR DESCRIPTION
**Pull request by baquer**
issue #112 
Show case implemented in Add to Calendar button.
screen shot 2018-07-25 at 1 40 14 am

### CODE REVIEW

**Comment by baquer** [comment]
@chashmeetsingh , @imjog , @SIMRAN1  review the PR.

**Review by jogendra — CHANGES_REQUESTED** [review]
ShowCase is showing everytime user open new event and also when opening the app again, which is very bad practice. ShowCase should only show one time. Use UserDefaults.

**Comment by baquer** [comment]
okay i will update the changes

**Review by SIMRAN1 — COMMENTED** [review]
please do changes as mentioned by @imjog !

**Comment by baquer** [comment]
@imjog  review the PR

**Comment by jogendra** [comment]
@baquer Please resolve the conflicts.

**Comment by baquer** [comment]
@jogendra , actually i deleted this branch from my local folder , so do you have any idea about recovering the branch ? or should i need to make a new PR for this?

**Comment by jogendra** [comment]
@baquer You may have deleted the branch from the local repo but it is still there on the remote.
`git fetch origin` to fetch your remote stuffs.

**Comment by baquer** [comment]
@jogendra thanks , will try this.

**Comment by baquer** [comment]
@jogendra , one problem is occurring that i have't this branch in my local folder, so , how can i switch to this branch and fetch origin ?? Please guide on this
The only solution i have is to make a new branch and fetch this branch from remote and after fetching this branch , again fetch the origin development and merge this branch , is it cool or any other alternative ??

**Comment by mariobehling** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
