### PR TITLE
Converting to swift4.2

### LINKED ISSUE #124: [UPDATE] Migrate Project To Swift 4.2
**Expected Behaviour**
Migrate project to 4.2

**Would You Like To Work On This**
Yes

### PR DESCRIPTION
**Pull request by SIMRAN1**
Fixes #124 
Converting to swift4.2

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@jogendra @chashmeetsingh I am getting circle ci test failed but its working fine on xcode. Please help me in this issue!

**Comment by jogendra** [comment]
@SIMRAN1 currently circle CI is using Xcode 9.3 which support Swift 4.1 only. You are using Swift 4.2, you need to updated Xcode version in Circle-CI config file.

**Comment by jogendra** [comment]
And Why not update to Swift 5.0?

**Comment by SIMRAN1** [comment]
thanks @jogendra  I will update the code to swift 5.0!!

**Comment by jogendra** [comment]
I am closing this PR, please make a PR for migration to Swift 5!

**Pull request closed without merging**
