### PR TITLE
Deleted .DS_Store files, added to .gitignore & resolved failing tests

### LINKED ISSUE #72: Add .DS_Store file to .gitignore
**Actual Behaviour**

Whenever anyone setup project on MacOS. MacOS generate the filename `.DS_Store` which contain custom attributes of its containing folder, such as the position of icons or the choice of a background image. The name is an abbreviation of Desktop Services Store, reflecting its purpose. Read more about `.DS_Store` file [here](https://en.wikipedia.org/wiki/.DS_Store).
Currently, `.DS_Store` file is not added in `.gitignore` file. 

**Expected Behaviour**

`.DS_Store` file should be added to `.gitignore` file. 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by jogendra**
Fixed #72 

Changes:
- Resolved the failing UI tests
- Added `.DS_Store` files to `.gitignore`
- Deleted existing `.DS_Store`

Screenshots:
N/A

### CODE REVIEW

**Comment by jogendra** [comment]
@mariobehling @chashmeetsingh Please review the PR and merge it. This is required for PR #57 , #69 and #70

**Review by SIMRAN1 — APPROVED** [review]

**Review by chashmeetsingh — APPROVED** [review]

**Review by SIMRAN1 — COMMENTED** [review]
var refreshControl = UIRefreshControl()  
@imjog its not added in DispatchQueue

**Comment by jogendra** [comment]
@SIMRAN1 That is not required! See tests are passing!

**Comment by SIMRAN1** [comment]
okk @imjog !!

**Pull request merged**
