### PR TITLE
Updates for swift 3

### PR DESCRIPTION
**Pull request by chashmeetsingh**

### CODE REVIEW

**Comment by mariobehling** [comment]
Please help to fix failing travis tests.

**Comment by mariobehling** [comment]
Well, I see travis is not added yet. Let's do it asap.

**Comment by chashmeetsingh** [comment]
thanks @mariobehling

**Comment by mariobehling** [comment]
Great to get you on board!

I opened this issue for tests and CI: https://github.com/fossasia/open-event-ios/issues/23

Please open issues and match PR with issues for future contributions. Thank you.

**Pull request merged**
