### PR TITLE
Fix continuous modal view presenting and icon sizes

### LINKED ISSUE #146: Update icon sizes for larger phone sizes
Please follow the issue template to **report a bug** 

**Actual Behaviour**
The profile icon appears much smaller than the other icons on larger phone sizes. The more icon is disproportionate and is offset. 

**Expected Behaviour**
The two tab bar icons should be properly positioned and sized.

**Steps to reproduce it**
View the main tab bar controller within the application.

**LogCat for the issue**
None

**Screenshots of the issue**
Screen Shot 2020-01-11 at 10 59 28 PM

-   Device: [e.g. iPhone 11 Pro Max]
-   OS: [e.g. iOS13]
-   Xcode version: [Version 11.3 (11C29)]

**Would you like to work on the issue?**
- [x] Yes!

### PR DESCRIPTION
**Pull request by pranavkarthik10**
Fixes #146 #144 
This included adding modalPresentationStyle so there are no recursive modals, changing icon sizes for higher resolutions for larger mobile sizes, pod updates.

Screencast:
Screen Recording 2020-01-11 at 10 42 51 PM

### CODE REVIEW

**Comment by pranavkarthik10** [comment]
@mariobehling @abishekvashok @Orbiter Please review and merge this! Thank you.

**Review by abishekvashok — CHANGES_REQUESTED** [review]
I see a lot of other files other than icons size changes, are they needed?

**Comment by pranavkarthik10** [comment]
@abishekvashok Yes you are right, reverted one extra file. The other change in the view controller is for the modal issue. Also updated pods which caused the Podfile.lock to be updated as well. @jogendra Please review this!

**Comment by pranavkarthik10** [comment]
@mariobehling @abishekvashok @Orbiter Please review and merge this! Thank you.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
